In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_excel('dataset.xlsx')

df.head()

sentiment   productId          userId  \
0         -1  B000EQYQBO  A2JZVE0Y19VLL0   
1         -1  B000LKVHYC  A3NAKOMAS0I5L9   
2         -1  B003QRQRY2   ARBO3XW14MNGA   
3         -1  B008EG58V8  A1IQXGT4MJUYJ8   
4          1  B004WZZY8M  A2TBL6WAZGXB9P   

                                             summary  \
0                                         blue chips   
1                             Bad even for 'healthy'   
2                          Alot of money for one can   
3  The Box says "OATMEAL SQUARES" which I believe...   
4                                         Delicious!   

                                                text  helpfulY  helpfulN  
0  The chips are okay Not near as flavorful as th...         0         0  
1  I had high hopes for this, but it was bad.  Re...         0         0  
2  I guess it's only one can since there is nothi...         1         1  
3  "Oatmeal Squares" is in about the largest prin...         0         0  
4  I really enjoyed this flavor, this has a very ...         1         0

In [3]:
df_test = pd.read_excel('test_set.xlsx')

df_test.head()

sentiment   productId          userId  \
0          1  B000SDKDM4  A1NE47S8ZJPLR3   
1          1  B000MS6CK2  A1GV419L0C3AJY   
2          1  B0030F70LO   A8EJ2H1P3ELL3   
3         -1  B001EO6GJK  A34R5COY8PP3LE   
4          1  B004SRH2B6  A23H9F74EMOXEF   

                                      summary  \
0                               Smooth coffee   
1                                     awesome   
2                 Great treat for bigger dogs   
3  Disappointing - more like candy than fruit   
4                              Good Product !   

                                                text  helpfulY  helpfulN  
0  My built-in Bosch coffee machine has trouble g...         0         0  
1  An absolute "must have" item for your Bloody M...         0         0  
2  I have a Great Dane & most treats are gone in ...         2         1  
3  I got turned on to dried mangoes from the ones...         0         1  
4  I enjoyed the product, good taste, good qualit...         0         1

In [4]:
m, n = df.shape

y_train = df.iloc[:, :1].values

X_train = df.iloc[:, n-2:n].values

y_list = []

for i in y_train:
    for j in i:
        y_list.append(j)
        
y_train = np.array(y_list)

y_train[:10]

array([-1, -1, -1, -1,  1, -1, -1,  1,  1,  1], dtype=int64)

In [5]:
m, n = df_test.shape

y_test = df_test.iloc[:, :1].values

X_test = df_test.iloc[:, n-2:n].values

y_list = []

for i in y_test:
    for j in i:
        y_list.append(j)
        
y_test = np.array(y_list)

y_test[:10]

array([ 1,  1,  1, -1,  1, -1,  1, -1, -1,  1], dtype=int64)

In [6]:
X_train[:10]

array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [5, 0],
       [0, 0]], dtype=int64)

In [7]:
X_test[:10]

array([[0, 0],
       [0, 0],
       [2, 1],
       [0, 1],
       [0, 1],
       [0, 5],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [8]:
sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test  = sc.fit_transform(X_test)

In [9]:
X_train.shape

(4000, 2)

In [10]:
y_train.shape

(4000,)

In [11]:
X_test.shape

(500, 2)

In [12]:
y_test.shape

(500,)

-------------

# myPerceptron

In [13]:
class myPerceptron(object):
    
    def __init__(self, epochs = 10, learning_rate = 0.01):
        self.epochs = epochs
        self.learning_rate = learning_rate
    
    def classify(self, X, y):
        (n_samples, n_features) = X.shape
        self.w = np.zeros(n_features)
        self.b = 0
        for t in range(0, self.epochs):
            for i in range(0, n_samples):
                pred = np.dot(self.w, X[i]) + self.b
                if(y[i] * pred <= 0):
                    self.w += -(1 / n_samples) * self.learning_rate * ((pred - y[i]) * X[i])
                    self.b += -(1 / n_samples) * self.learning_rate * (pred - y[i])
        return (self.w, self.b)
    
    def predict(self, X):
        (n_samples, n_features) = X.shape
        self.predictions = np.zeros(n_samples)
        for i in range(0, n_samples):
            x = X[i]
            self.prediction = np.dot(self.w, x) + self.b
            if(self.prediction > 0):
                self.predictions[i] = 1
            else:
                self.predictions[i] = -1
        return self.predictions
    
    def accuracy(self, predictions, y):
        return (predictions == y).mean()

--------------------

In [14]:
my_perceptron = myPerceptron()

In [15]:
my_perceptron.classify(X_train, y_train)

(array([ 1.86028466e-06, -4.66516849e-06]), 1.1046364924566984e-08)

In [16]:
y_pred_train = my_perceptron.predict(X_train)

y_pred_train[:10]

array([ 1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
my_perceptron.accuracy(y_pred_train, y_train)

0.64175

-------------------

In [18]:
y_pred_test = my_perceptron.predict(X_test)

In [19]:
my_perceptron.accuracy(y_pred_test, y_test)

0.642

--------------------

In [20]:
perceptron = Perceptron()

perceptron.fit(X_train, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [21]:
y_pred_train = perceptron.predict(X_train)

y_pred_train[:10]

array([ 1,  1, -1,  1,  1,  1,  1,  1,  1,  1], dtype=int64)

In [22]:
accuracy_score(y_train, y_pred_train)

0.639

In [23]:
y_pred_test = perceptron.predict(X_test)

y_pred_test[:10]

array([ 1,  1, -1, -1, -1, -1,  1,  1,  1,  1], dtype=int64)

In [24]:
accuracy_score(y_test, y_pred_test)

0.638

---------------